### ISSUE TITLE
Chromatogram Directory

### ISSUE THREAD

**Issue by singjc** [shubham1637/DIAlignR#12]
Is it possible to change the assumed chromatogram files folder to something more general? Like **xics** or **chromatograms**? Because I usually store my **sqMass** files in a folder called **sqmass**, not **mzml** since they're not **mzML** files, which causes an issue with [get_filenames.R#L84](https://github.com/shubham1637/DIAlignR/blob/22e33506e0abf22e745f2fc1075eaaf237437e47/R/get_filenames.R#L84).

It's not a problem to just rename the folder to **mzml**, more so just a personal preference..

**Comment by shubham1637** [comment]
Right. I think we can change the name to `xics`. Currently, I have both `.chrom.mzML` and `.chrom.sqMass` files in mzml folder. I provide a flag to decide which file type to choose.
You can change the name and create pull request. I can merge it then

**Comment by singjc** [comment]
Great, I made a [PR](https://github.com/shubham1637/DIAlignR/pull/13).
